apps/home/urls.py
from django.urls import path, re_path
from . import views

app_name = 'home'

urlpatterns = [
    # The home page
    path('', views.index, name='home'),
    path('register-cpanel/', views.register_cpanel, name='register_cpanel'),
    path('delete-cpanel/<int:task_id>', views.delete_cpanel, name='delete_cpanel'),
    path('update-cpanel/<int:task_id>', views.update_cpanel, name='update_cpanel'),
    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),

]

tunneling_hub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register

    # ADD NEW Routes HERE

    # Leave `Home.Urls` as last the last line
    path("", include("apps.home.urls"))
]

apps/templates/includes/navigation.html
<!-- [ Header ] start -->
<header class="navbar pcoded-header navbar-expand-lg navbar-light">
    <div class="m-header">
        <a class="mobile-menu" id="mobile-collapse1" href="javascript:"><span></span></a>
        <a href="/" class="b-brand">
            <div class="b-bg">
                <i class="feather icon-trending-up"></i>
            </div>
            <span class="b-title">Datta Able</span>
        </a>
    </div>
    <a class="mobile-menu" id="mobile-header" href="javascript:">
        <i class="feather icon-more-horizontal"></i>
    </a>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li><a href="javascript:" class="full-screen" onclick="javascript:toggleFullScreen()"><i
                    class="feather icon-maximize"></i></a></li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown">Dropdown</a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="javascript:">Action</a></li>
                    <li><a class="dropdown-item" href="javascript:">Another action</a></li>
                    <li><a class="dropdown-item" href="javascript:">Something else here</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <div class="main-search">
                    <div class="input-group">
                        <input type="text" id="m-search" class="form-control" placeholder="Search . . .">
                        <a href="javascript:" class="input-group-append search-close">
                            <i class="feather icon-x input-group-text"></i>
                        </a>
                        <span class="input-group-append search-btn btn btn-primary">
                                <i class="feather icon-search input-group-text"></i>
                            </span>
                    </div>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li>
                <label>
                    <i class="icon feather icon-sun" id="theme-indicator"></i>
                    <input type="checkbox" id="theme-switch" class="d-none">
                </label>
            </li>
            <li>
                <div class="dropdown">
                    <a class="dropdown-toggle" href="javascript:" data-toggle="dropdown"><i
                            class="icon feather icon-bell"></i></a>
                    <div class="dropdown-menu dropdown-menu-right notification">
                        <div class="noti-head">
                            <h6 class="d-inline-block m-b-0">Notifications</h6>
                            <div class="float-right">
                                <a href="javascript:" class="m-r-10">mark as read</a>
                                <a href="javascript:">clear all</a>
                            </div>
                        </div>
                        <ul class="noti-body">
                            <li class="n-title">
                                <p class="m-b-0">NEW</p>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="{{ ASSETS_ROOT }}/images/user/avatar-1.jpg"
                                        alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>John Doe</strong><span class="n-time text-muted"><i
                                                class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                        <p>New ticket Added</p>
                                    </div>
                                </div>
                            </li>
                            <li class="n-title">
                                <p class="m-b-0">EARLIER</p>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="{{ ASSETS_ROOT }}/images/user/avatar-2.jpg"
                                        alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>Joseph William</strong><span class="n-time text-muted"><i
                                                class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                        <p>Prchace New Theme and make payment</p>
                                    </div>
                                </div>
                            </li>
                            <li class="notification">
                                <div class="media">
                                    <img class="img-radius" src="{{ ASSETS_ROOT }}/images/user/avatar-3.jpg"
                                        alt="Generic placeholder image">
                                    <div class="media-body">
                                        <p><strong>Sara Soudein</strong><span class="n-time text-muted"><i
                                                class="icon feather icon-clock m-r-10"></i>30 min</span></p>
                                        <p>currently login</p>
                                    </div>
                                </div>
                            </li>
                        </ul>
                        <div class="noti-footer">
                            <a href="javascript:">show all</a>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="dropdown drp-user">
                    <a href="javascript:" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon feather icon-settings"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right profile-notification">
                        <div class="pro-head">
                            <img src="{{ ASSETS_ROOT }}/images/user/avatar-1.jpg" class="img-radius" alt="User-Profile-Image">
                            <span>
                                {{ request.user.username }}    
                            </span>
                            <a href="/auth-signin.html" class="dud-logout" title="Logout">
                                <i class="feather icon-log-out"></i>
                            </a>
                        </div>
                        <ul class="pro-body">
                            <li><a href="/profile.html" class="dropdown-item"><i class="feather icon-user"></i>
                                Profile</a></li>
                            <li><a href="{% url 'logout' %}" class="dropdown-item">
                                <i class="feather icon-lock"></i> Logout</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</header>
<!-- [ Header ] end -->

apps/templates/includes/scripts.html
<script src="{{ ASSETS_ROOT }}/js/vendor-all.js"></script>
<script src="{{ ASSETS_ROOT }}/plugins/bootstrap/js/bootstrap.min.js"></script>
<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script> -->

<script src="{{ ASSETS_ROOT }}/js/pcoded.js"></script>
<script src="{{ ASSETS_ROOT }}/js/dark-mode.js"></script>

apps/templates/includes/sidebar.html
<!-- [ navigation menu ] start -->
<nav class="pcoded-navbar">
    <div class="navbar-wrapper">
        <div class="navbar-brand header-logo">
            <a href="/" class="b-brand">
                <div class="b-bg">
                    <i class="feather icon-trending-up"></i>
                </div>
                <span class="b-title">Datta Able</span>
            </a>
            <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
        </div>
        <div class="navbar-content scroll-div">
            <ul class="nav pcoded-inner-navbar">
                <li class="nav-item pcoded-menu-caption">
                    <label>Navigation</label>
                </li>
                <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project" 
                    class="nav-item {% if 'index' in segment %} active {% endif %}">
                    <a href="/" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span
                            class="pcoded-mtext">Dashboard</span></a>
                </li>
                <li data-username="Profile Page" 
                    class="nav-item {% if 'profile' in segment %} active {% endif %}">
                    <a href="/profile.html" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-user"></i></span>
                            <span class="pcoded-mtext">Profile Page</span></a>
                </li> 
                <li data-username="Register Cpanel" 
                    class="nav-item {% if 'register-cpanel' in segment %} active {% endif %}">
                    <a href="{% url 'home:register_cpanel' %}" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-cpu"></i></span>
                            <span class="pcoded-mtext">Register Cpanel</span></a>
                </li>              
                <li class="nav-item pcoded-menu-caption">
                    <label>UI Element</label>
                </li>
                <li data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds"
                    class="nav-item pcoded-hasmenu ">
                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-box"></i></span><span
                            class="pcoded-mtext">Components</span></a>
                    <ul class="pcoded-submenu">
                        <li class=""><a href="/bc_button.html" class="">Button</a></li>
                        <li class=""><a href="/bc_badges.html" class="">Badges</a></li>
                        <li class=""><a href="/bc_breadcrumb-pagination.html" class="">Breadcrumb & paggination</a></li>
                        <li class=""><a href="/bc_collapse.html" class="">Collapse</a></li>
                        <li class=""><a href="/bc_tabs.html" class="">Tabs & pills</a></li>
                        <li class=""><a href="/bc_typography.html" class="">Typography</a></li>


                        <li class=""><a href="/icon-feather.html" class="">Feather<span
                                class="pcoded-badge label label-danger">NEW</span></a></li>
                    </ul>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Forms & table</label>
                </li>
                <li data-username="form elements advance componant validation masking wizard picker select"
                    class="nav-item {% if 'form_elements' in segment %} active {% endif %}">
                    <a href="/form_elements.html" class="nav-link "><span class="pcoded-micon"><i
                            class="feather icon-file-text"></i></span><span
                            class="pcoded-mtext">Form elements</span></a>
                </li>
                <li data-username="Table bootstrap datatable footable" 
                    class="nav-item {% if 'tbl_bootstrap' in segment %} active {% endif %}">
                    <a href="/tbl_bootstrap.html" class="nav-link "><span class="pcoded-micon"><i
                            class="feather icon-server"></i></span><span class="pcoded-mtext">Table</span></a>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Chart & Maps</label>
                </li>
                <li data-username="Charts Morris" 
                    class="nav-item {% if 'chart-morris' in segment %} active {% endif %}">
                    <a href="/chart-morris.html" class="nav-link "><span
                        class="pcoded-micon"><i class="feather icon-pie-chart"></i></span><span class="pcoded-mtext">Chart</span></a>
                </li>
                <li data-username="Maps Google" 
                    class="nav-item {% if 'map-google' in segment %} active {% endif %}">
                    <a href="/map-google.html" class="nav-link "><span
                        class="pcoded-micon"><i class="feather icon-map"></i></span><span
                        class="pcoded-mtext">Maps</span></a></li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Pages</label>
                </li>
                <li data-username="Authentication Sign up Sign in reset password Change password Personal information profile settings map form subscribe"
                    class="nav-item pcoded-hasmenu">
                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-lock"></i></span><span
                            class="pcoded-mtext">Authentication</span></a>
                    <ul class="pcoded-submenu">
                        <li class=""><a href="/register.html" class="" target="_blank">Sign UP</a></li>
                        <li class=""><a href="/login.html" class="" target="_blank">Sign IN</a></li>
                    </ul>
                </li>

                <li data-username="Sample Page" class="nav-item"><a href="/page-blank.html" class="nav-link"><span
                        class="pcoded-micon"><i class="feather icon-sidebar"></i></span><span class="pcoded-mtext">Sample page</span></a>
                </li>

                <li data-username="Disabled Menu" class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-power"></i></span><span class="pcoded-mtext">Logout</span>
                    </a>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>More Resources</label>
                </li>                    
                <li data-username="Support Page" class="nav-item ">
                    <a target="_blank" href="https://appseed.us/support" class="nav-link">
                        <span class="pcoded-micon">
                            <i class="feather icon-headphones"></i>
                        </span>
                        <span class="pcoded-mtext">Support</span>
                    </a>
                </li>                
            </ul>
        </div>
    </div>
</nav>
<!-- [ navigation menu ] end -->